"""Routing-agnostic tenant registry service.

Manages the tenant lifecycle: register → activate → rename/resolve slug.
NEVER connects to a tenant dsn (routing-agnostic — the load-bearing separation
between the control plane and the tenant's physical database, which is Phase 2).

Public API
----------
register_tenant(session, name, *, slug, dsn=None, status="provisioning") -> Tenant
activate_tenant(session, tenant_id) -> Tenant
get_tenant(session, tenant_id) -> Tenant | None
get_tenant_dsn(session, tenant_id) -> str
rename_slug(session, tenant_id, new_slug) -> None
resolve_slug(session, slug) -> tuple[str, bool] | None
"""

from __future__ import annotations

import re
from datetime import datetime, timedelta, timezone

from sqlalchemy.orm import Session

from ...db.control import repository as control_repo
from ...db.control.models.tenant import Tenant, _opaque_id

# tenant_id is used as a DB-name component in Phase 2 (CREATE DATABASE …<id>).
# Constrain to a safe charset so it can never break a quoted identifier.
_TENANT_ID_RE = re.compile(r"^[a-z0-9_]+$")

# DNS-label: [a-z0-9], may contain hyphens (not leading/trailing), ≤63 chars (RFC 1123).
_SLUG_RE = re.compile(r"^[a-z0-9]([a-z0-9-]*[a-z0-9])?$")

# How long a renamed slug is reserved for redirect and squat protection.
SLUG_COOLING_DAYS: int = 30


# ── input validators ──────────────────────────────────────────────────────────


def _validate_tenant_id(tenant_id: str) -> None:
    """Raise ValueError if tenant_id contains unsafe characters for a DB-name component."""
    if not _TENANT_ID_RE.match(tenant_id):
        raise ValueError(
            f"invalid tenant_id {tenant_id!r}: must match {_TENANT_ID_RE.pattern} "
            "(lowercase letters, digits, underscore only)"
        )


def _validate_slug(slug: str) -> None:
    """Raise ValueError if slug is not a valid RFC-1123 DNS label (≤63 chars)."""
    if not slug or not _SLUG_RE.match(slug) or len(slug) > 63:
        raise ValueError(
            f"invalid slug {slug!r}: must be a DNS label — "
            "[a-z0-9], optional interior hyphens, ≤63 chars"
        )


def _assert_slug_claimable(session: Session, slug: str) -> None:
    """Raise ValueError if the slug is NOT claimable.

    A slug is claimable only when it is BOTH:
    - not a live tenant.slug (no current tenant owns it), AND
    - not in TenantSlugHistory with reserved_until > now (cooling window).
    """
    live_id = control_repo.live_slug_tenant_id(session, slug)
    if live_id is not None:
        raise ValueError(f"slug {slug!r} is already taken by tenant {live_id!r}")
    if control_repo.is_slug_cooling(session, slug):
        raise ValueError(
            f"slug {slug!r} is in a cooling/reserved window and is not yet claimable"
        )


# ── lifecycle operations ───────────────────────────────────────────────────────


def register_tenant(
    session: Session,
    name: str,
    *,
    slug: str,
    dsn: str | None = None,
    status: str = "provisioning",
) -> Tenant:
    """Register a new tenant with an OPAQUE, auto-generated id.

    The id is generated by the model's default (_opaque_id — a uuid4 hex string)
    and is NEVER derived from the slug. The tenant is created with status
    'provisioning' by default; the caller must activate it after physical
    provisioning is complete (Phase 2).

    When ``dsn`` is ``None`` (the default), the DSN is derived from the
    opaque id via ``default_tenant_dsn(tenant_id)`` after the id is minted,
    preserving the opaque-id invariant (the id is still server-generated,
    never derived from the slug).  Pass an explicit ``dsn`` to override
    (bring-your-own-DSN provision).

    Validates:
    - slug is a valid DNS label
    - slug is not a live tenant.slug
    - slug is not in a cooling TenantSlugHistory row

    Never connects to ``dsn`` (routing-agnostic).
    """
    _validate_slug(slug)
    _assert_slug_claimable(session, slug)

    # id is generated by the model's default=_opaque_id, never passed in or
    # derived from the slug — the opaque-id invariant is structural here.
    tenant_id = _opaque_id()
    _validate_tenant_id(tenant_id)  # belt-and-suspenders: _opaque_id always passes

    if dsn is None:
        from .dsn import (
            default_tenant_dsn,
        )  # local import: avoids circular at module load

        dsn = default_tenant_dsn(tenant_id)

    return control_repo.add_tenant(
        session,
        id=tenant_id,
        name=name,
        slug=slug,
        dsn=dsn,
        status=status,
    )


def activate_tenant(session: Session, tenant_id: str) -> Tenant:
    """Flip the tenant status to 'active' and return the updated Tenant.

    Raises LookupError if the tenant is not found.
    """
    t = control_repo.get_tenant(session, tenant_id)
    if t is None:
        raise LookupError(f"tenant {tenant_id!r} not found")
    t.status = "active"
    session.flush()
    return t


def get_tenant(session: Session, tenant_id: str) -> Tenant | None:
    """Return the Tenant with this id, or None if not found."""
    return control_repo.get_tenant(session, tenant_id)


def get_tenant_dsn(session: Session, tenant_id: str) -> str:
    """Return the DSN string for a tenant.

    Raises LookupError if the tenant is not found.
    Never connects to the returned DSN (routing-agnostic).
    """
    dsn = control_repo.get_tenant_dsn(session, tenant_id)
    if dsn is None:
        raise LookupError(f"tenant {tenant_id!r} not found")
    return dsn


# ── slug lifecycle ─────────────────────────────────────────────────────────────


def rename_slug(
    session: Session,
    tenant_id: str,
    new_slug: str,
) -> None:
    """Rename a tenant's slug with a cooling/redirect window on the old slug.

    Steps (in one session flush):
    1. Validate new_slug is a DNS label and claimable.
    2. Look up the tenant; raise LookupError if not found.
    3. Insert the old slug into TenantSlugHistory with reserved_until = now + SLUG_COOLING_DAYS.
    4. Set tenant.slug = new_slug.

    After this call, ``resolve_slug(old_slug)`` returns ``(tenant_id, True)`` (redirect)
    until the cooling window expires.
    """
    _validate_slug(new_slug)
    _assert_slug_claimable(session, new_slug)

    t = control_repo.get_tenant(session, tenant_id)
    if t is None:
        raise LookupError(f"tenant {tenant_id!r} not found")

    old_slug = t.slug
    reserved_until = datetime.now(timezone.utc) + timedelta(days=SLUG_COOLING_DAYS)

    control_repo.add_slug_history(
        session,
        slug=old_slug,
        tenant_id=tenant_id,
        reserved_until=reserved_until,
    )
    t.slug = new_slug
    session.flush()


def resolve_slug(session: Session, slug: str) -> tuple[str, bool] | None:
    """Resolve a slug to a (tenant_id, redirect) pair, or None.

    Returns:
    - ``(tenant_id, False)`` — slug is a live tenant.slug (no redirect needed).
    - ``(tenant_id, True)``  — slug is retired but cooling (reserved_until > now);
                               the caller should issue a 301 to the live slug.
    - ``None``               — slug is unknown, expired (reserved_until ≤ now), or
                               history with no cooling window.
    """
    # 1. Check for a live tenant
    live_id = control_repo.live_slug_tenant_id(session, slug)
    if live_id is not None:
        return (live_id, False)

    # 2. Check slug history
    hist = control_repo.get_slug_history(session, slug)
    if hist is None:
        return None

    # A history row is a redirect only while the cooling window is active.
    if hist.reserved_until is not None and hist.reserved_until > datetime.now(
        timezone.utc
    ):
        return (hist.tenant_id, True)

    # Expired or no cooling window → not claimable for redirect
    return None
