"""AuthN routes: signup (founder), login, logout, set-password / invite-accept, ``/auth/me``.

Identity lives entirely in the CONTROL plane (users / sessions / memberships). Signup registers
a tenant in the control-plane registry and activates it (Phase 1 is routing-agnostic — physical
per-tenant DB provisioning is Phase 2); it never touches a tenant DB. All DB work runs on the
request's ``control_session``.

Security posture:
- **Signup is FAIL-CLOSED** (de-fork B-F1 + A-F9): off in ``prod`` (404), and in ``staging`` it is
  DENIED unless ``signup_allowlist`` is populated (empty allowlist on staging ⇒ 403, the opposite
  of the reference's "empty = unrestricted"). Open only in ``dev``. A consumer opts into staging
  signups by populating ``signup_allowlist``; see ``.env.example`` / README.
- Login is constant-ish-time + non-enumerating: the absent-user and disabled-user paths still spend
  a verify against a cached dummy hash, and every failure returns the same generic 401. Login mints
  a **fresh** session (no pre-auth session is ever adopted ⇒ session fixation is structurally
  prevented).
- Signup collisions (email or slug) return one generic 409 that never says which collided — no
  account/tenant enumeration.
- set-password redeems an invite token atomically (single-use via a conditional UPDATE … RETURNING),
  sets the password, stamps the membership's ``accepted_at``, and **invalidates ALL of the user's
  existing sessions** (a credential reset must not leave old sessions live — B-F11: any future
  logged-in change-password / account-disable flow MUST replicate this ``delete Session WHERE
  user_id`` step).
"""

from __future__ import annotations

import functools
import uuid
from datetime import datetime, timedelta, timezone

from fastapi import APIRouter, Depends, HTTPException, Request, Response, status
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field
from sqlalchemy import delete, select, update
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from ...config.settings import get_settings
from ...db.control import models as m
from ..authn.email_norm import canonicalize
from ..authn.passwords import hash_password, needs_rehash, verify_password
from ..authn.tokens import hash_token, mint
from ..authz.service import add_membership
from ..cookies import set_session_cookie
from ..deps import control_session, current_user
from ..tenancy.registry import activate_tenant, register_tenant, resolve_slug

router = APIRouter()

_GENERIC_BAD_REQUEST = "Invalid request"
_INVALID_CREDENTIALS = "Invalid credentials"
_GENERIC_SIGNUP_COLLISION = "Could not complete signup"

# A routing-agnostic Phase-1 placeholder DSN. The registry NEVER connects to it (Phase 2 wires
# physical per-tenant routing); it only persists the string.
_PLACEHOLDER_DSN = "postgresql+psycopg://unprovisioned/placeholder"


class SignupBody(BaseModel):
    email: str = Field(max_length=320)  # RFC 5321 max email length
    password: str = Field(min_length=12, max_length=1024)  # policy floor + DoS cap
    tenant_name: str = Field(max_length=200)
    # The human-friendly DNS-label slug the founder requests. The tenant's id is OPAQUE and
    # auto-generated by the registry — never derived from the slug (a de-fork invariant).
    slug: str = Field(max_length=63)


class LoginBody(BaseModel):
    email: str
    # Cap only — NO min, so existing/legacy passwords below the new floor still attempt (and fail
    # generically) rather than 422-leaking that they're too short.
    password: str = Field(max_length=1024)


class SetPasswordBody(BaseModel):
    token: str
    password: str = Field(min_length=12, max_length=1024)


def _now() -> datetime:
    return datetime.now(timezone.utc)


@functools.cache
def _dummy_hash() -> str:
    """A cached argon2 hash so the absent-/disabled-user login path still spends comparable CPU
    (no timing oracle distinguishing "no such user" from "wrong password")."""
    return hash_password("invalid-sentinel-password")


def _issue_session(s: Session, user_id: uuid.UUID) -> str:
    """Mint a session row for *user_id*; return the raw token to hand to the client (once)."""
    settings = get_settings()
    raw, token_hash = mint()
    s.add(
        m.Session(
            token_hash=token_hash,
            user_id=user_id,
            expires_at=_now() + timedelta(hours=settings.session_ttl_hours),
        )
    )
    return raw


def _allowlisted(email_canonical: str) -> bool:
    """True iff *email_canonical* matches the signup allowlist.

    An empty allowlist returns True here (the per-environment fail-closed policy is applied by the
    signup handler, NOT here): an entry is either an exact email, or a domain suffix starting '@'.
    """
    allowlist = get_settings().signup_allowlist
    if not allowlist:
        return True
    for entry in allowlist:
        entry_l = entry.strip().lower()
        if entry_l.startswith("@"):
            if email_canonical.endswith(entry_l):
                return True
        elif email_canonical == entry_l:
            return True
    return False


@router.post("/auth/signup", status_code=status.HTTP_201_CREATED)
def signup(body: SignupBody, s: Session = Depends(control_session)) -> JSONResponse:
    settings = get_settings()

    # 1. FAIL-CLOSED env gating (de-fork B-F1 + A-F9).
    #    - prod: signup is OFF — return 404 so the endpoint's very existence isn't advertised.
    #    - dev: the ONLY explicitly-open environment (empty allowlist permitted).
    #    - EVERY other non-prod env (staging, test, and any future token): DENY unless the allowlist
    #      is both POPULATED and MATCHES the email (⇒ 403). This flips the reference's "empty =
    #      unrestricted" default AND is fail-closed for unknown env tokens — a value the gate doesn't
    #      explicitly recognize (e.g. APP_ENVIRONMENT=test) must require an allowlist, never fall
    #      through to open. A consumer opts in by populating signup_allowlist.
    if settings.environment == "prod":
        raise HTTPException(status_code=404, detail="Not found")

    # Canonicalize BEFORE the allowlist check (the allowlist matches on the canonical form).
    try:
        email_canonical = canonicalize(body.email)
    except ValueError:
        raise HTTPException(status_code=400, detail=_GENERIC_BAD_REQUEST) from None

    if settings.environment != "dev":
        if not settings.signup_allowlist or not _allowlisted(email_canonical):
            raise HTTPException(status_code=403, detail="Signup not permitted")

    # 3. Cheap collision checks BEFORE registering the tenant — one generic 409 that never reveals
    #    which of email/slug collided (no enumeration). Pre-checking the slug here (live OR cooling,
    #    via resolve_slug) keeps register_tenant's only residual ValueError the bad-charset case →
    #    a deterministic 400 below. It also avoids leaving an orphan tenant row when the email is
    #    taken.
    if (
        s.scalar(
            select(m.AppUser.id).where(m.AppUser.email_canonical == email_canonical)
        )
        is not None
        or resolve_slug(s, body.slug) is not None
    ):
        raise HTTPException(status_code=409, detail=_GENERIC_SIGNUP_COLLISION)

    # 4. Register + activate the tenant (control-plane only; routing-agnostic). A bad-charset slug
    #    is the only residual ValueError → generic 400 (the collision case was pre-checked above).
    #    The slug column is DB-UNIQUE, so a TOCTOU race against the resolve_slug pre-check surfaces
    #    here as an IntegrityError → the SAME generic 409 as a pre-checked collision (no enumeration,
    #    and never a 500 on the race).
    try:
        tenant = register_tenant(
            s, body.tenant_name, slug=body.slug, dsn=_PLACEHOLDER_DSN
        )
        s.flush()
    except ValueError:
        s.rollback()
        raise HTTPException(status_code=400, detail=_GENERIC_BAD_REQUEST) from None
    except IntegrityError:
        s.rollback()
        raise HTTPException(status_code=409, detail=_GENERIC_SIGNUP_COLLISION) from None

    # 5–7. Found the user + admin membership + session. Collisions (email/slug) → one generic 409.
    try:
        activate_tenant(s, tenant.id)
        user = m.AppUser(
            email=body.email,
            email_canonical=email_canonical,
            password_hash=hash_password(body.password),
            born="signup",
            signed_up_at=_now(),
        )
        s.add(user)
        s.flush()
        add_membership(
            s,
            user_id=user.id,
            tenant_id=tenant.id,
            role_name=settings.admin_role_name,
            actor_id=user.id,
            invited=False,
        )
        raw = _issue_session(s, user.id)
        s.commit()
    except IntegrityError:
        s.rollback()
        raise HTTPException(status_code=409, detail=_GENERIC_SIGNUP_COLLISION) from None

    response = JSONResponse(
        {"tenant_id": tenant.id, "slug": body.slug},
        status_code=status.HTTP_201_CREATED,
    )
    set_session_cookie(response, raw)
    return response


@router.post("/auth/login")
def login(body: LoginBody, s: Session = Depends(control_session)) -> JSONResponse:
    user: m.AppUser | None = None
    try:
        email_canonical = canonicalize(body.email)
    except ValueError:
        # Treat malformed as no-user (still spends a verify below — no enumeration).
        email_canonical = None
    if email_canonical is not None:
        user = s.scalar(
            select(m.AppUser).where(m.AppUser.email_canonical == email_canonical)
        )

    # Constant-ish-time: ALWAYS run a verify so the absent-user path spends comparable CPU.
    if user is None or user.password_hash is None:
        verify_password(body.password, _dummy_hash())  # discard — no enumeration
        raise HTTPException(status_code=401, detail=_INVALID_CREDENTIALS)
    if (
        not verify_password(body.password, user.password_hash)
        or user.disabled_at is not None
    ):
        raise HTTPException(status_code=401, detail=_INVALID_CREDENTIALS)

    if needs_rehash(user.password_hash):
        user.password_hash = hash_password(body.password)
    # A FRESH session is minted — no pre-auth session is ever adopted, so fixation is structurally
    # impossible (there is no caller-supplied session id to "fixate" on).
    raw = _issue_session(s, user.id)
    s.commit()

    response = JSONResponse({"ok": True}, status_code=200)
    set_session_cookie(response, raw)
    return response


@router.post("/auth/logout", status_code=status.HTTP_204_NO_CONTENT)
def logout(request: Request, s: Session = Depends(control_session)) -> Response:
    settings = get_settings()
    raw = request.cookies.get(settings.session_cookie_name)
    if not raw:
        header = request.headers.get("authorization", "")
        if header.lower().startswith("bearer "):
            raw = header[7:]
    raw = (raw or "").strip()
    if raw:
        s.execute(delete(m.Session).where(m.Session.token_hash == hash_token(raw)))
        s.commit()
    response = Response(status_code=status.HTTP_204_NO_CONTENT)
    response.delete_cookie(settings.session_cookie_name)
    return response


@router.post("/auth/set-password", status_code=status.HTTP_204_NO_CONTENT)
def set_password(
    body: SetPasswordBody, s: Session = Depends(control_session)
) -> Response:
    now = _now()
    # Atomic single-use redemption: the conditional UPDATE only matches an unused, unexpired token,
    # and stamps used_at in the same statement — so two concurrent redemptions can't both win.
    row = s.execute(
        update(m.InviteToken)
        .where(
            m.InviteToken.token_hash == hash_token(body.token),
            m.InviteToken.used_at.is_(None),
            m.InviteToken.expires_at > now,
        )
        .values(used_at=now)
        .returning(m.InviteToken.user_id, m.InviteToken.membership_id)
    ).first()
    if row is None:
        # Generic — never distinguish unknown vs used vs expired.
        raise HTTPException(status_code=400, detail="Invalid or expired token")

    user = s.get(m.AppUser, row.user_id)
    if user is not None:
        user.password_hash = hash_password(body.password)
    if row.membership_id is not None:
        membership = s.get(m.TenantMembership, row.membership_id)
        if membership is not None:
            membership.accepted_at = now

    # Invalidate EVERY existing session for this user (set-password is also a credential reset).
    # B-F11: any future logged-in change-password / disable flow MUST replicate this step.
    s.execute(delete(m.Session).where(m.Session.user_id == row.user_id))
    s.commit()
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@router.get("/auth/me")
def me(
    user: m.AppUser = Depends(current_user),
    s: Session = Depends(control_session),
) -> dict:
    memberships = s.scalars(
        select(m.TenantMembership).where(m.TenantMembership.user_id == user.id)
    ).all()
    out = []
    for membership in memberships:
        roles = list(
            s.scalars(
                select(m.Role.name)
                .join(
                    m.TenantRoleAssignment,
                    m.TenantRoleAssignment.role_id == m.Role.id,
                )
                .where(m.TenantRoleAssignment.membership_id == membership.id)
            ).all()
        )
        out.append({"tenant_id": membership.tenant_id, "roles": roles})
    return {"id": str(user.id), "email": user.email, "memberships": out}
